### ISSUE TITLE
New Version: asio.hpp: No such file or directory

### ISSUE THREAD

**Issue by Sarah26-10** [platformio/platform-ststm32#633] opened 2022-06-17 11:25 UTC
Hello there,

today i tried to work on my Portenta project, which compiled and worked some weeks ago. Until now i had to reinstall PIO.
When i now build the project the following error occurs in every portenta projects and configurations:
**fatal error: asio.hpp: No such file or directory**

I found the solution in degrading the platform version to: 

> platform = ststm32@15.3.0

So my question: Is there an error in the new Version with this **asio.hpp**?

**Comment by valeros** [comment] 2022-07-05 08:35
Hi @Sarah26-10 ! Seems like you have an old broken package, try to force PlatformIO redownload the framework package by deleting the folder `c:\Users\YOUR_USER\.platformio\packages\framework-arduino-mbed` (`/home/YOUR_USER/.platformio/packages/framework-arduino-mbed` on Linux) and compile your project again.

**Comment by Sarah26-10** [comment] 2022-07-05 09:37
No, problem still occurs.

**Comment by valeros** [comment] 2022-07-13 18:51
@Sarah26-10 Could you please put together a simple example to reproduce the issue?

**Comment by valeros** [comment] 2023-06-14 12:00
Closing this issue because it needs more information and has not had recent activity.

**Closed by valeros** 2023-06-14 12:00 UTC
