### ISSUE TITLE
<command-line>: fatal error: variant_BLACKPILL_F401Cx.h: No such file or directory

### ISSUE THREAD

**Issue by rvbnsk** [platformio/platform-ststm32#681] opened 2023-03-02 12:41 UTC
Hi,
upgraded from ststm32@15.4.1 to ststm32@15.5.0. 

Code does not not build due to missing file variant_BLACKPILL_F401Cx.h.
The problem was not visible on version ststm32@15.4.1

Actual config:
- pio core 6.1.6

platformio.ini:
```ini
[env:blackpill_f411ce]
platform = ststm32
board = blackpill_f411ce
framework = arduino
build_unflags = -std=gnu++14
build_flags = -std=gnu++17
...
```

**Comment by valeros** [comment] 2023-03-02 12:50
Duplicate of #680, but thanks for reporting. A fix is already available in the development branch, a new release will be published today.

**Closed by valeros** 2023-03-02 12:50 UTC
