### ISSUE TITLE
Support for Arduino Portenta

### ISSUE THREAD

**Issue by JSCLadon** [platformio/platform-ststm32#483] opened 2021-01-02 15:19 UTC
Arduino Portenta: Very interesting board, but no support from platformio?

**Comment by MaffooClock** [comment] 2021-02-23 16:28
Duplicate of #457.

**Comment by utkarshsethi** [comment] 2021-05-07 09:56
@valeros you can close this too, duplicate of #494 & #457.

@JSCLadon This has already been resolved in #494, released in [12.1.0](https://github.com/platformio/platform-ststm32/releases/tag/v12.1.0).

**Closed** 2021-05-07 09:57 UTC
