### ISSUE TITLE
DFU upload problems with Arduino GIGA R1

### ISSUE THREAD

**Issue by storskegg** [platformio/platform-ststm32#812] opened 2024-11-08 23:47 UTC
# DFU Upload Problems

Board: Arduino GIGA R1 (M7 core)

This issue relates to the conversation found here: https://community.platformio.org/t/giga-dfu-issues/41982/11

While sketches successfully load onto the device from the Arduino IDE, I'm unable to upload firmware via `pio`.

Something worth noting here, and I mentioned it in the above conversation, I noticed that the USB device ID changes when it switches from normal "monitor" mode to DFU. I wonder if the switch causes a desync in `dfu-tool`?

Please let me know if there is a better place to submit this issue, or if there's more info that I can provide.

## CLI Output

I've included the cli output, including...

- device list before and after (omitting unrelated devices, etc) the call to upload the firmware
- The appropriate `dfu-util --version`
- A note re: the device id

```
> pio device list
/dev/cu.usbmodem1101
--------------------
Hardware ID: USB VID:PID=2341:0266 SER=002200233033510936383737 LOCATION=1-1
Description: Giga

> /Users/liam/.platformio/packages/tool-dfuutil-arduino/dfu-util --version
dfu-util 0.11-arduino4

Copyright 2005-2009 Weston Schmidt, Harald Welte and OpenMoko Inc.
Copyright 2010-2021 Tormod Volden and Stefan Schmidt
This program is Free Software and has ABSOLUTELY NO WARRANTY
Please report bugs to http://sourceforge.net/p/dfu-util/tickets/


> pio run -t upload -v
Processing giga_r1_m7 (platform: ststm32; framework: arduino; board: giga_r1_m7; build_flags: -D DEBUG; upload_protocol: dfu)
------------
CONFIGURATION: https://docs.platformio.org/page/boards/ststm32/giga_r1_m7.html
PLATFORM: ST STM32 (17.6.0) > Arduino Giga R1 (M7 core)
HARDWARE: STM32H747XIH6 480MHz, 511.35KB RAM, 768KB Flash
DEBUG: Current (cmsis-dap) External (cmsis-dap, jlink, stlink)
PACKAGES:
 - framework-arduino-mbed @ 4.1.5
 - tool-dfuutil-arduino @ 1.11.0
 - tool-openocd @ 3.1200.0 (12.0)
 - tool-stm32duino @ 1.0.1
 - toolchain-gccarmnoneeabi @ 1.70201.0 (7.2.1)
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 42 compatible libraries
Scanning dependencies...
No dependencies
Building in release mode
MethodWrapper(["checkprogsize"], [".pio/build/giga_r1_m7/firmware.elf"])
Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
RAM:   [=         ]   8.7% (used 45456 bytes from 523624 bytes)
Flash: [=         ]  13.1% (used 102736 bytes from 786432 bytes)
.pio/build/giga_r1_m7/firmware.elf  :
section              size        addr
.text               98832   134479872
.ARM.extab            612   134578704
.ARM.exidx           1240   134579316
.data                2664   603979776
.uninitialized         24   603982440
.bss                42792   603982464
.openamp_section        0   939524096
.pdm_section        64512   939524096
.heap              477784   604025256
.lwip_sec          278528   805306368
.ARM.attributes        44           0
.comment              202           0
.debug_frame         8376           0
.stab                  60           0
.stabstr              118           0
Total              975788
<lambda>(["upload"], [".pio/build/giga_r1_m7/firmware.bin"])
AVAILABLE: cmsis-dap, dfu, jlink, mbed, stlink
CURRENT: upload_protocol = dfu
BeforeUpload(["upload"], [".pio/build/giga_r1_m7/firmware.bin"])
Auto-detected: /dev/cu.usbmodem1101
Forcing reset using 1200bps open/close on port /dev/cu.usbmodem1101
Waiting for the new upload port...
"/Users/liam/.platformio/packages/tool-dfuutil-arduino/dfu-util" -d 0x2341:0x0366,0x2341:0x0266,0x2341:0x0466 -a 0 -s 0x08040000:leave -D "/Users/liam/Documents/Arduino/audio-spectrum-analyzer/.pio/build/giga_r1_m7/firmware.bin"
dfu-util 0.11-arduino4

Copyright 2005-2009 Weston Schmidt, Harald Welte and OpenMoko Inc.
Copyright 2010-2021 Tormod Volden and Stefan Schmidt
This program is Free Software and has ABSOLUTELY NO WARRANTY
Please report bugs to http://sourceforge.net/p/dfu-util/tickets/

dfu-util: No DFU capable USB device available
*** [upload] Error 74
====== [FAILED] Took 2.27 seconds ======

> echo The device successfully switched to, and remains in DFU mode
The device successfully switched to, and remains in DFU mode

> pio device list
/dev/cu.usbmodem1102
--------------------
Hardware ID: USB VID:PID=2341:0366 SER=002200233033510936383737 LOCATION=1-1
Description: Giga

>
```

**Comment by valeros** [comment] 2024-11-11 10:49
Duplicate of #794, fixed in the dev branch.

**Closed by valeros** 2024-11-11 10:49 UTC
