### ISSUE TITLE
Add Board Support for Arduino Giga.

### ISSUE THREAD

**Issue by braydenanderson2014** [platformio/platform-ststm32#743] opened 2023-11-23 07:45 UTC
As far as I can tell, it seems the Arduino Giga does not exist on PlatformIO. I am trying to code a library for the Giga, and it does not come up in the board list.

### Additional info
Arduino Giga utilizes the mbed os. At least according to the research ive been able to find. The board has a STM32H747XI Microcontroller and it supports micropython. Im not sure if im putting this "issue" in the right place, i tried looking at the list of repositories but i am unsure which category it falls under.

**Comment by valeros** [comment] 2023-11-23 10:00
Seems like duplicate of https://github.com/platformio/platform-ststm32/issues/702

**Closed by valeros** 2023-11-23 10:00 UTC
