### ISSUE TITLE
Unknown upload protocol serial

### ISSUE THREAD

**Issue by chantincheung** [platformio/platform-ststm32#155] opened 2018-10-28 08:21 UTC
It's documented that STM32F103C8 (20k RAM. 64k Flash) supports the next uploading protocols:
```
jlink
stlink
blackmagic
serial
dfu
```

But I got warning，the log is：
```
Processing genericSTM32F103C8 (framework: stm32cube; platform: ststm32; board: genericSTM32F103C8)
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/ststm32/genericSTM32F103C8.html
PLATFORM: ST STM32 > STM32F103C8 (20k RAM. 64k Flash)
SYSTEM: STM32F103C8T6 72MHz 20KB RAM (64KB Flash)
DEBUG: CURRENT(blackmagic) EXTERNAL(blackmagic, jlink, stlink)
Warning! Cannot find a linker script for the required board! Firmware will be linked with a default linker script!
Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF MODES: FINDER(chain) COMPATIBILITY(soft)
Collected 0 compatible libraries
Scanning dependencies...
No dependencies
Warning! Unknown upload protocol serial
Checking size .pioenvs\genericSTM32F103C8\firmware.elf
Memory Usage -> http://bit.ly/pio-memory-usage
DATA:    [          ]   0.2% (used 44 bytes from 20480 bytes)
PROGRAM: [          ]   1.9% (used 1248 bytes from 65536 bytes)
======================================================================= [SUCCESS] Took 2.45 seconds =======================================================================
```
My platformio.ini:
```
[env:genericSTM32F103C8]
platform = ststm32
framework = stm32cube
board = genericSTM32F103C8
upload_protocol = serial
upload_port = COM5
upload_speed = 115200
build_flags = -DF1
```
ENV:WIN10，VSC

**Comment by ivankravets** [comment] 2018-12-11 20:31
Duplicate of https://github.com/platformio/platform-ststm32/issues/164

**Closed by ivankravets** 2018-12-11 20:31 UTC
